Refactor commit-msg script to use a default configuration file path and improve error handling. - Remove the parameter `$1` used to pass a configuration file path to the script. - Set `CONFIG_FILE` variable to the default path `./.anyhooksrc` if it is not already set. - Remove the check for the existence of `$CONFIG_FILE` and sourcing it. - If `$CONFIG_FILE` does not exist, print an error message stating that the configuration file is not found. - Print the reason for the error, which is that the script requires the configuration file for sourcing variables. - Add a user task to make sure that the configuration file exists and is accessible. - Exit with code 6 to indicate an error condition. These changes aim to simplify the script's usage, make the default configuration file path explicit, and provide clear error messages and tasks for the user to resolve the issue.

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -63,18 +63,12 @@ if ! command -v openssl &> /dev/null; then
 fi
 
 # Source the variable
-CONFIG_FILE="$1"
-if [ ! -z "$CONFIG_FILE" ] && [ -f $CONFIG_FILE ]; then
-    echo "CONFIG_FILE $CONFIG_FILE"
-    source $CONFIG_FILE
-else
-    CONFIG_FILE="./.anyhooksrc"
-    if [ ! -f $CONFIG_FILE ]; then
-        echo "Error: Configuration file $CONFIG_FILE not found."
-        echo "Reason: The script requires this file for sourcing variables."
-        echo "User Task: Make sure $CONFIG_FILE exists and is accessible."
-        exit 6
-    fi
+CONFIG_FILE="./.anyhooksrc"
+if [ ! -f $CONFIG_FILE ]; then
+    echo "Error: Configuration file $CONFIG_FILE not found."
+    echo "Reason: The script requires this file for sourcing variables."
+    echo "User Task: Make sure $CONFIG_FILE exists and is accessible."
+    exit 6
 fi
 
 # Check for required files and variables
